// Tool IDs have type `ToolID`
const TOOL_FREE_FORM_SELECT = "TOOL_FREE_FORM_SELECT";
const TOOL_SELECT = "TOOL_SELECT";
const TOOL_ERASER = "TOOL_ERASER";
const TOOL_FILL = "TOOL_FILL";
const TOOL_PICK_COLOR = "TOOL_PICK_COLOR";
const TOOL_MAGNIFIER = "TOOL_MAGNIFIER";
const TOOL_PENCIL = "TOOL_PENCIL";
const TOOL_BRUSH = "TOOL_BRUSH";
const TOOL_AIRBRUSH = "TOOL_AIRBRUSH";
const TOOL_TEXT = "TOOL_TEXT";
const TOOL_LINE = "TOOL_LINE";
const TOOL_CURVE = "TOOL_CURVE";
const TOOL_RECTANGLE = "TOOL_RECTANGLE";
const TOOL_POLYGON = "TOOL_POLYGON";
const TOOL_ELLIPSE = "TOOL_ELLIPSE";
const TOOL_ROUNDED_RECTANGLE = "TOOL_ROUNDED_RECTANGLE";


export {
  TOOL_AIRBRUSH,
  TOOL_BRUSH,
  TOOL_CURVE,
  TOOL_ELLIPSE,
  TOOL_ERASER,
  TOOL_FILL,
  TOOL_FREE_FORM_SELECT,
  TOOL_LINE,
  TOOL_MAGNIFIER,
  TOOL_PENCIL,
  TOOL_PICK_COLOR,
  TOOL_POLYGON,
  TOOL_RECTANGLE,
  TOOL_ROUNDED_RECTANGLE,
  TOOL_SELECT,
  TOOL_TEXT
};
